export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const NAVBARS_REPOSITORY = 'NAVBARS_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY';
export const MENUS_REPOSITORY = 'MENUS_REPOSITORY';
export const MENUS_CHILDREN_REPOSITORY = 'MENUS_CHILDREN_REPOSITORY';

